"""自動運用ジョブ定義（ダッシュボード・automation_control 共通）。"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class AutomationJob:
    id: str
    name: str
    category: str
    schedule: str
    detail: str
    path: str
    launchd: str
    default_on: bool
    status: str = "active"
    alert: str = ""
    channel_key: str = ""  # Buffer チャネル（buffer-* 用）
    kill_patterns: tuple[str, ...] = ()  # enforce 時に終了するプロセス識別子


FAS = "10_Projects/GEO Search Protocol/form-auto-sender"

AUTOMATION_JOBS: tuple[AutomationJob, ...] = (
    AutomationJob(
        id="form-auto-sender",
        name="フォーム自動送信",
        category="sales",
        schedule="毎日 10:00",
        detail="run_scheduled.sh → main.py · 上限300件/日",
        path=f"{FAS}/run_scheduled.sh",
        launchd="com.coaretail.form-auto-sender",
        default_on=True,
        kill_patterns=("form-auto-sender/main.py",),
    ),
    AutomationJob(
        id="sales-daily-collect",
        name="営業リスト収集",
        category="sales",
        schedule="毎日 11:00〜15:00（毎時）",
        detail="daily_collect.js · 日次上限400件 · 業種優先キャンペーン（6業種・中古車販売4番目）",
        path="40_Sales/営業自動化ツール/daily_collect.js",
        launchd="com.coaretail.sales.daily_collect",
        default_on=True,
        kill_patterns=("daily_collect.js",),
    ),
    AutomationJob(
        id="reservation-daily-ward",
        name="パーソナルジムクローラー · 1日1区フル診断",
        category="sales",
        schedule="毎日 18:00",
        detail="daily_fitness_ward_diagnosis.py · FIT Search · 23区ローテ（リスト+予約+ARI）",
        path="40_Sales/営業自動化ツール/reservation_crawler/run_daily_ward.sh",
        launchd="com.coaretail.reservation.daily_ward",
        default_on=True,
        kill_patterns=("daily_fitness_ward_diagnosis.py",),
    ),
    AutomationJob(
        id="ops-dashboard",
        name="運用ダッシュボード再生成",
        category="sales",
        schedule="1時間ごと",
        detail="build_ops_dashboard.py",
        path=f"{FAS}/build_ops_dashboard.py",
        launchd="com.coaretail.ops-dashboard",
        default_on=True,
    ),
    AutomationJob(
        id="qol-buffer-daily",
        name="QOL 7ch Buffer 予約投入",
        category="buffer",
        schedule="毎日 18:30",
        detail="upload_qol_x_buffer.py",
        path="10_Projects/QOLmedia/rakuten-affiliate/rakuten-x-affiliate/run_daily.sh",
        launchd="com.qolmedia.rakuten.daily",
        default_on=True,
        kill_patterns=("upload_qol_x_buffer.py",),
    ),
    AutomationJob(
        id="buffer-fatigue",
        name="Buffer · fatigue",
        category="buffer",
        schedule="翌日 08:00",
        detail="x_posts_fatigue_49.csv",
        path="10_Projects/QOLmedia/x_posts_fatigue_49.csv",
        launchd="（qol-buffer-daily 内）",
        default_on=True,
        channel_key="fatigue",
    ),
    AutomationJob(
        id="buffer-focus",
        name="Buffer · focus",
        category="buffer",
        schedule="翌日 12:00",
        detail="x_posts_focus_49.csv",
        path="10_Projects/QOLmedia/x_posts_focus_49.csv",
        launchd="（qol-buffer-daily 内）",
        default_on=True,
        channel_key="focus",
    ),
    AutomationJob(
        id="buffer-stress",
        name="Buffer · stress",
        category="buffer",
        schedule="翌日 18:00",
        detail="x_posts_stress_49.csv",
        path="10_Projects/QOLmedia/x_posts_stress_49.csv",
        launchd="（qol-buffer-daily 内）",
        default_on=True,
        channel_key="stress",
    ),
    AutomationJob(
        id="buffer-sleep",
        name="Buffer · sleep",
        category="buffer",
        schedule="翌日 21:00",
        detail="x_posts_sleep_49.csv",
        path="10_Projects/QOLmedia/x_posts_sleep_49.csv",
        launchd="（qol-buffer-daily 内）",
        default_on=True,
        channel_key="sleep",
    ),
    AutomationJob(
        id="buffer-haircare",
        name="Buffer · haircare",
        category="buffer",
        schedule="翌日 23:00",
        detail="x_posts_hc_49.csv",
        path="10_Projects/QOLmedia/x_posts_hc_49.csv",
        launchd="（qol-buffer-daily 内）",
        default_on=True,
        channel_key="haircare",
    ),
    AutomationJob(
        id="qol-weekly-mon",
        name="QOLmedia 週次レポート",
        category="weekly",
        schedule="月曜 09:00",
        detail="qol_weekly_report.py",
        path="10_Projects/QOLmedia/scripts/run_weekly_report.sh",
        launchd="com.qolmedia.qol.weekly.mon",
        default_on=True,
    ),
    AutomationJob(
        id="qol-weekly-fri",
        name="QOLmedia 週次レポート",
        category="weekly",
        schedule="金曜 17:00",
        detail="qol_weekly_report.py",
        path="10_Projects/QOLmedia/scripts/run_weekly_report.sh",
        launchd="com.qolmedia.qol.weekly.fri",
        default_on=True,
    ),
    AutomationJob(
        id="geo-weekly-mon",
        name="GEO LP 週次レポート",
        category="weekly",
        schedule="月曜 09:05",
        detail="geo_lp_weekly_report.py",
        path="10_Projects/GEO Search Protocol/scripts/run_weekly_report.sh",
        launchd="com.coaretail.geo.weekly.mon",
        default_on=True,
    ),
    AutomationJob(
        id="geo-weekly-fri",
        name="GEO LP 週次レポート",
        category="weekly",
        schedule="金曜 17:05",
        detail="geo_lp_weekly_report.py",
        path="10_Projects/GEO Search Protocol/scripts/run_weekly_report.sh",
        launchd="com.coaretail.geo.weekly.fri",
        default_on=True,
    ),
    AutomationJob(
        id="localgeo-weekly-mon",
        name="Local GEO 週次レポート",
        category="weekly",
        schedule="月曜 09:10",
        detail="localgeo weekly",
        path="10_Projects/Local GEO/scripts/run_weekly_report.sh",
        launchd="com.coaretail.localgeo.weekly.mon",
        default_on=True,
    ),
    AutomationJob(
        id="localgeo-weekly-fri",
        name="Local GEO 週次レポート",
        category="weekly",
        schedule="金曜 17:10",
        detail="localgeo weekly",
        path="10_Projects/Local GEO/scripts/run_weekly_report.sh",
        launchd="com.coaretail.localgeo.weekly.fri",
        default_on=True,
    ),
    AutomationJob(
        id="bumblebee-weekly",
        name="Bumblebee 週次スキャン",
        category="other",
        schedule="日曜 09:00",
        detail="Vault 外スクリプト",
        path="~/.local/bin/bumblebee-weekly-scan.sh",
        launchd="com.coaretail.bumblebee-weekly",
        default_on=True,
        kill_patterns=("bumblebee-weekly-scan.sh",),
    ),
    AutomationJob(
        id="rakuten-pipeline",
        name="楽天アフィ日次パイプライン",
        category="stopped",
        schedule="—",
        detail="2026-06-06 停止",
        path="10_Projects/QOLmedia/archive/deprecated/",
        launchd="—",
        default_on=False,
        status="stopped",
    ),
    AutomationJob(
        id="buffer-pet",
        name="Buffer · pet",
        category="buffer",
        schedule="翌日 15:00",
        detail="x_posts_pet_49.csv",
        path="10_Projects/QOLmedia/x_posts_pet_49.csv",
        launchd="（qol-buffer-daily 内）",
        default_on=True,
        channel_key="pet",
    ),
    AutomationJob(
        id="buffer-factoring",
        name="Buffer · factoring",
        category="buffer",
        schedule="翌日 20:00",
        detail="x_posts_factoring_49.csv",
        path="10_Projects/QOLmedia/x_posts_factoring_49.csv",
        launchd="（qol-buffer-daily 内）",
        default_on=True,
        channel_key="factoring",
    ),
    AutomationJob(
        id="buffer-rakuten",
        name="Buffer · rakuten",
        category="stopped",
        schedule="—",
        detail="2026-06-06 停止",
        path="10_Projects/QOLmedia/archive/deprecated/",
        launchd="—",
        default_on=False,
        status="stopped",
    ),
    AutomationJob(
        id="rakuten-generate-old",
        name="旧 launchd（楽天3分割）",
        category="stopped",
        schedule="—",
        detail="rakuten.daily に統合",
        path="10_Projects/QOLmedia/rakuten-affiliate/rakuten-x-affiliate/launchd/",
        launchd="com.qolmedia.rakuten.generate 等",
        default_on=False,
        status="stopped",
    ),
    AutomationJob(
        id="retry-errors-once",
        name="エラー再実行（一回限り）",
        category="stopped",
        schedule="手動",
        detail="retry_errors.py",
        path=f"{FAS}/launchd/",
        launchd="com.coaretail.retry-errors",
        default_on=False,
        status="stopped",
    ),
    AutomationJob(
        id="daily-routine",
        name="デイリーノート自動生成",
        category="attention",
        schedule="毎日 08:00",
        detail="daily_routine.sh 欠落",
        path="10_Projects/scripts/daily_routine.sh",
        launchd="com.coaretail.daily-routine",
        default_on=False,
        status="error",
        alert="スクリプト欠落 — launchd 連続エラー",
    ),
    AutomationJob(
        id="retry-0519",
        name="エラー再実行（2026-05-19）",
        category="attention",
        schedule="一回限り",
        detail="plist 残存",
        path=f"{FAS}/launchd/",
        launchd="com.coaretail.retry-0519",
        default_on=False,
        status="error",
        alert="unload 推奨",
    ),
    AutomationJob(
        id="google-ads-exclusion",
        name="Google Ads プレースメント自動除外",
        category="other",
        schedule="毎日 06:00 JST",
        detail="hair / SLEEP / PET GDN · GitHub Actions → main.py",
        path="70_outputs/Ads/google/scripts/main.py",
        launchd="GitHub Actions (CME0358/ads-automation)",
        default_on=True,
        status="active",
        alert="",
    ),
)

JOBS_BY_ID: dict[str, AutomationJob] = {j.id: j for j in AUTOMATION_JOBS}

CHANNEL_JOB_BY_KEY: dict[str, str] = {
    j.channel_key: j.id for j in AUTOMATION_JOBS if j.channel_key
}

AUTO_CATEGORIES: dict[str, str] = {
    "sales": "営業・GEO（日次）",
    "buffer": "Buffer / X 投稿",
    "weekly": "週次レポート",
    "other": "その他",
    "stopped": "停止済み（2026-06-06〜）",
    "attention": "要対応 / 未確認",
}
